apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: blazor
  name: blazor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blazor
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: blazor
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          image: blazor:latest
          name: blazor
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
