apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: webapi
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: webapi
    spec:
      containers:
        - command:
            - dotnet
            - WebApi.dll
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          envFrom:
            - configMapRef:
                name: my-env-secret
          image: webapi:latest
          name: webapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
