name: CI Build, Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: calculadora11
          POSTGRES_DB: VIATAB
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_USER: postgres
      DB_PASSWORD: calculadora11
      DB_NAME: VIATAB
      DB_HOST: localhost
      DB_PORT: 5432
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: docker-compose build

      - name: Tag and push images
        run: |
          docker tag webapi ${{ secrets.DOCKER_USERNAME }}/webapi:latest
          docker tag blazor ${{ secrets.DOCKER_USERNAME }}/blazor:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/webapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/blazor:latest
